---
include: create.yml

# This is here to draw attention to the fact that
# this file exists.  You can use it when defining
# this role in an error-handling scenario on a
# failed OS build. It will delete the VM that has
# been created.
include: destroy.yml
when: false
